export const text = {
  heart:
    "The heart is a muscular organ in most animals. This organ pumps blood through the blood vessels of the circulatory system.[1] The pumped blood carries oxygen and nutrients to the body, while carrying metabolic waste such as carbon dioxide to the lungs.[2] In humans, the heart is approximately the size of a closed fist and is located between the lungs, in the middle compartment of the chest, called the mediastinum.",
  thyroid:
    "The thyroid, or thyroid gland, is an endocrine gland in vertebrates. In humans, it is in the neck and consists of two connected lobes. The lower two thirds of the lobes are connected by a thin band of tissue called the isthmus. The thyroid gland is a butterfly-shaped gland located in the neck below the Adam's apple. Microscopically, the functional unit of the thyroid gland is the spherical thyroid follicle, lined with follicular cells (thyrocytes), and occasional parafollicular cells that surround a lumen containing colloid. The thyroid gland secretes three hormones: the two thyroid hormones - triiodothyronine (T3) and thyroxine (T4) - and a peptide hormone, calcitonin. The thyroid hormones influence the metabolic rate and protein synthesis and growth and development in children.",
  liver:
    "The liver is a major metabolic organ only found in vertebrate animals, which performs many essential biological functions such as detoxification of the organism, and the synthesis of proteins and biochemicals necessary for digestion and growth.In humans, it is located in the right upper quadrant of the abdomen, below the diaphragm and mostly shielded by the lower right rib cage. Its other metabolic roles include carbohydrate metabolism, the production of hormones, conversion and storage of nutrients such as glucose and glycogen, and the decomposition of red blood cells.",
  brian:
    "The brain (or encephalon) is an organ that serves as the center of the nervous system in all vertebrate and most invertebrate animals. The brain is the largest cluster of neurons in the body and is typically located in the head, usually near organs for special senses such as vision, hearing and olfaction. It is the most specialized and energy-consuming organ in the body, responsible for complex sensory perception, motor control, endocrine regulation and the development of intelligence.",
  stomach:
    "The stomach is a muscular, hollow organ in the gastrointestinal tract of humans and many other animals, including several invertebrates. The stomach has a dilated structure and functions as a vital organ in the digestive system. The stomach is involved in the gastric phase of digestion, following chewing. It performs a chemical breakdown by means of enzymes and hydrochloric acid. In humans and many other animals, the stomach is located between the esophagus and the small intestine. The stomach secretes digestive enzymes and gastric acid to aid in food digestion. The pyloric sphincter controls the passage of partially digested food (chyme) from the stomach into the duodenum, where peristalsis takes over to move this through the rest of the intestines.",
  intestine:
    'The gastrointestinal tract (GI tract, digestive tract, alimentary canal) is the tract or passageway of the digestive system that leads from the mouth to the anus. The GI tract contains all the major organs of the digestive system, in humans and other animals, including the esophagus, stomach, and intestines. Food taken in through the mouth is digested to extract nutrients and absorb energy, and the waste expelled at the anus as faeces. Gastrointestinal is an adjective meaning of or pertaining to the stomach and intestines.Most animals have a "through-gut" or complete digestive tract. Exceptions are more primitive ones: sponges have small pores (ostia) throughout their body for digestion and a larger dorsal pore (osculum) for excretion, comb jellies have both a ventral mouth and dorsal anal pores, while cnidarians and acoels have a single pore for both digestion and excretion.',
  bladder:
    "The bladder is a hollow organ in humans and other vertebrates that stores urine from the kidneys before disposal by urination. In humans the bladder is a distensible organ that sits on the pelvic floor. Urine enters the bladder via the ureters and exits via the urethra. The typical adult human bladder will hold between 300 and 500 ml (10.14 and 16.91 fl oz) before the urge to empty occurs, but can hold considerably more.",
  kidneys:
    "In humans, the kidneys are two reddish-brown bean-shaped blood-filtering organs that are a multilobar, multipapillary form of mammalian kidneys, usually without signs of external lobulation. They are located on the left and right in the retroperitoneal space, and in adult humans are about 12 centimetres (4.5 inches) in length. They receive blood from the paired renal arteries; blood exits into the paired renal veins. Each kidney is attached to a ureter, a tube that carries excreted urine to the bladder.",
  lungs:
    "The lungs are the primary organs of the respiratory system in humans and most other animals, including some snails and a small number of fish. In mammals and most other vertebrates, two lungs are located near the backbone on either side of the heart. Their function in the respiratory system is to extract oxygen from the air and transfer it into the bloodstream, and to release carbon dioxide from the bloodstream into the atmosphere, in a process of gas exchange. The pleurae, which are thin, smooth, and moist, serve to reduce friction between the lungs and chest wall during breathing, allowing for easy and effortless movements of the lungs.",
};

export function capitalize(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
}

//const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
